### ISSUE TITLE
Safari without sound

### ISSUE THREAD

**Issue by soerenray** [Renumics/spotlight#27]
**Describe the bug**
When using Spotlight on Safari, Audio Files produce no sound when clicking on the play button

**To Reproduce**
1. Open Spotlight with an audio dataset
2. Click on a sample
3. Add audio view
4. Press play

**Expected behavior**
Sound should be played

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Browser Version general problem, independent of version
 - Spotlight Version newest

**Comment by steffenslavetinsky** [comment]
After looking into this I think that there actually are 2 problems with Apples Safari.

@soerenray can you confirm that this is a Safari problem and that it is working in other Browsers in your setup?

Problem 1:

Afaik `autoplay` is disabled for audio in safari and is only enabled after a user interaction (a click for example). Obviously there is a click event, as we have to click a button before the audio is played but Safari does not link the `onClick` callback from react to the actual html `click` event therefore the audio is not allowed to `autoplay`

Problem 2:

I think that Safari is not able to interpret the blob src `blob:http://localhost:5000/...` without a type being specified on the audio source.

In my tests Problem 2 could be resolved by specifying source with a type:

So instead of:

```jsx
<audio ref={audioRef} src={url} />
```

we could specify the audios type by adding a `source` tag:

```jsx
<audio ref={audioRef}>
  <source src={url} type="audio/wav" />
</audio>
```


In order to solve Problem 1 we need to directly link the user interaction to audioElement and play a sound on the first interaction. I believe that when we did this once, we should be able to play sounds on this audio element without further user interaction.

In my test I added an eventListener to the button and played the current `url`. This worked but we might need to change how the AudioViewer plays sounds in order to use this approach.

```typescript
useEffect(() => {
    if (url === undefined) return;

    const audioElement = audioRef.current;
    if (!audioElement) return;

    const audioSource = audioSourceRef.current;
    if (!audioSource) return;

    const button = playPauseButtonRef.current;
    if (!button) return;

    const playSound = () => {
        audioElement.load();
        audioSource.src = url;
        audioElement.play();
    };

    button.addEventListener('click', playSound);

    return () => button.removeEventListener('click', playSound);
}, [url]);
```
