### ISSUE TITLE
how to draw picture with ground truth bounding boxes and prediction bounding boxes in Inspector tab?

### ISSUE THREAD

**Issue by achen1959** [Renumics/spotlight#452]
**Is your feature request related to a problem? Please describe.**
Please describe the problem or motivation behind your feature request. For example, "I find it difficult to [...]"

**Describe the solution you'd like**
Provide a clear and concise description of the feature or enhancement you would like to see implemented.

**Describe alternatives you've considered**
Discuss any alternative solutions or features you have considered, explaining the pros and cons of each.

**Additional context**
Include any additional context, examples, or screenshots that can help illustrate your feature request.
This can assist in providing a better understanding of your proposal.

**Comment by druzsan** [comment]
Hi @achen1959, I'm not quite sure what is your problem exactly without context, but let's start with the basics.

Here is a minimal example of dataset with bounding boxes:
```python
import pandas as pd
from renumics import spotlight

image = (
    "https://spotlightpublic.blob.core.windows.net/internal-test-data/nature-360p.jpg"
)
df = pd.DataFrame(
    {
        "image": [image, image, image],
        "bbox": [[0.1, 0.1, 0.9, 0.3], [0.1, 0.3, 0.9, 0.6], [0.2, 0.6, 0.7, 0.7]],
        "category": ["sky", "mountains", "water"],
    }
)
df["category"] = df["category"].astype("category")
```

From now on, you can show your dataset (`spotlight.show(df)`). You can setup BB lens manually by adding a new lens in the inspector settings at bottom right. In the dropdown, select image and bouding box (and optionally category) columns and click on **Add View**.

To setup BB lens programmatically, add the following code to the example above:
```python
from renumics.spotlight import layout, layouts
from renumics.spotlight.layout import lenses

default_layout = layouts.default()
default_layout.children[1].children[0] = layout.inspector(
    lenses=[lenses.bounding_box("image", "bbox", "category")]
)
spotlight.show(df, layout=default_layout)
```

Regarding your mentioning of GT BBs **and** predition BBs in inspector, Spotlight cannot display multiple BB columns in the same BB lens at the same time, but you can:
- create 2 BB lenses and display image + GT BBs in one of them and image + predition BBs in another one;
- or,  if you need to see both types of BBs in the same lens, you can merge your GT and prediction BBs together into one single list of BBs per row and distinguish them by generating lists with labels of the same length.

**Comment by druzsan** [comment]
@achen1959  In order to show GT and prediction BBs together, you can do the following.
1. Let's imagine you have the following dataset:
```python
image = (
    "https://spotlightpublic.blob.core.windows.net/internal-test-data/nature-360p.jpg"
)
df = pd.DataFrame(
    {
        "image": [image, image, image],
        "bbox_gt": [[0.1, 0.1, 0.9, 0.3], [0.1, 0.3, 0.9, 0.6], [0.2, 0.6, 0.7, 0.7]],
        "label_gt": ["sky", "mountains", "water"],
        "bbox_pred": [
            [0.15, 0.05, 0.7, 0.25],
            [0.1, 0.4, 0.9, 0.7],
            [0.3, 0.6, 0.8, 0.7],
        ],
        "label_pred": ["water", "hills", "water"],
    }
)
```
Here you have a single prediction (`bbox_pred` and `label_pred`) and a respective GT (`bbox_gt` and `label_gt`) per dataset row.
If you setup the Spotlight layout programmatically, and show the dataset:
```python
df["label_gt"] = df["label_gt"].astype("category")
df["label_pred"] = df["label_pred"].astype("category")

default_layout = layouts.default()
default_layout.children[1].children[0] = layout.inspector(
    lenses=[
        lenses.bounding_box("image", "bbox_gt", "label_gt"),
        lenses.bounding_box("image", "bbox_pred", "label_pred"),
    ]
)
spotlight.show(df, layout=default_layout)
```

You will get the following appearance (be aware that the colors are picked up independently for each column, so both GT sky and prediction water are green by accident):

![image](https://github.com/Renumics/spotlight/assets/14849849/f6508244-9d09-4abe-b3ab-df7b81e8238b)

2. Now if you want to show both GT and prediction BBs together in the same image, add their BBs and labels to lists with two elements per row:

```python
df["bboxes"] = df.apply(lambda row: [row["bbox_gt"], row["bbox_pred"]], axis=1)
df["labels"] = df.apply(
    lambda row: [row["label_gt"] + "(GT)", row["label_pred"] + "(pred)"], axis=1
)
default_layout = layouts.default()
default_layout.children[1].children[0] = layout.inspector(
    lenses=[lenses.bounding_box("image", "bboxes", "labels")]
)
spotlight.show(df, layout=default_layout)
```

You will get the following appearance (colors are now gone since `labels` is not a category column anymore):

![image](https://github.com/Renumics/spotlight/assets/14849849/0a9db860-d733-427c-9855-fcf14683d8ee)

3. Finally, if you want to show all GT and prediction BBs per image or you don't have 1 to 1 connection between GTs and predictions, you cant group the dataset by image (`default_layout` is the same as in case 2):

```python
df = (
    df.groupby("image")
    .agg({"bboxes": lambda x: sum(x, []), "labels": lambda x: sum(x, [])})
    .reset_index(drop=False)
)
spotlight.show(df, layout=default_layout)
```

You will get the following appearance, though it can be too messy for many BBs per image:

![image](https://github.com/Renumics/spotlight/assets/14849849/29c4d2fe-1278-4b68-a6e5-4df553bbe1c5)

**Comment by druzsan** [comment]
Closed as solved, reported by @achen1959
